---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204

before_install:
  # Pull container.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  # Run tests.
  - ${PWD}/tests/test.sh ${distro}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
