---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the correct timezone.
  file: src=/usr/share/zoneinfo/{{ ntp_timezone }}  dest=/etc/localtime state=link force=yes

- name: Install NTP on RHEL flavors.
  yum: name=ntp state=installed
  when: ansible_os_family == 'RedHat'

- name: Install NTP on Debian flavors.
  apt: name=ntp state=installed
  when: ansible_os_family == 'Debian'

- name: Ensure NTP is running.
  service: name={{ ntp_daemon }} state=started enabled=yes
